#!/bin/sh
clean() {
  for d in */ ; do
    if [ "$d" = "lib/" ]; then
      continue
    fi
    find "$d" ! -name 'PKGBUILD' -type f -exec rm -f {} +
    find "$d" ! -name "$(echo "$d" | sed 's:/*$::')" -type d -exec rm -rf {} +
    rm -rf "$d$d"
  done
}

install_all() {
  for d in */ ; do
    cd "$d" || exit 1
    makepkg -si
    cd ..
  done
}

build_all() {
  for d in */ ; do
    cd "$d" || exit 1
    makepkg -si
    cd ..
  done
}

install() {
  cd "$1" || exit 1
  makepkg -si
  cd ..
}

build() {
  cd "$1" || exit 1
  makepkg -f
  cd ..
}


if [ "$1" = "clean" ]; then
  clean
  exit 0
fi

if [ "$1" = "install_all" ]; then
  install_all
  exit 0
fi

if [ "$1" = "build_all" ]; then
  build_all
  exit 0
fi

if [ "$1" = "install" ]; then
  install "$2"
  exit 0
fi
if [ "$1" = "build" ]; then
  build "$2"
  exit 0
fi


echo A valid command was not specified.
echo Try: clean, build, install, build_all or install_all.
exit 1